# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Petra Borovska
tagline:          'A Jekyll theme'
description:      'Short introduction'
url:              "https://petabor.github.io"
baseurl:          "/personal-web"
github_username:  petabor

author:
  name:           'Petra Borovska'
  url:            www.linkedin.com/in/petra-borovská-b6a579152

paginate:         5

# Custom vars
version:          2.1.0

# github:
#   repo:           https://github.com/petabor

plugins:
  - jekyll-gist
  - jekyll-paginate

